name: myparflowenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - geopandas
  - rasterio
  - matplotlib
  - numpy
  - pip
  - pip:
    - pftools[pfb]         # 通过 pip 安装 pftools 和 ParFlow I/O 组件
    - -e .                 # 以可编辑模式安装你的 myparflowtools 包
